import Main from '__views/Main';

// 不作为Main组件的子页面展示的页面单独写，如下
export const loginRouter = {
    path: '/login',
    name: 'login',
    meta: {
        title: 'Login - 登录'
    },
    component: resolve => { require(['@/views/login.vue'], resolve); }
};
export const page404 = {
    path: '/*',
    name: 'error-404',
    meta: {
        title: '404-页面不存在'
    },
    component: resolve => { require(['@/views/error-page/404.vue'], resolve); }
};

export const page403 = {
    path: '/403',
    meta: {
        title: '403-权限不足'
    },
    name: 'error-403',
    component: resolve => { require(['@//views/error-page/403.vue'], resolve); }
};

export const page500 = {
    path: '/500',
    meta: {
        title: '500-服务端错误'
    },
    name: 'error-500',
    component: resolve => { require(['@/views/error-page/500.vue'], resolve); }
};

export const preview = {
    path: '/preview',
    name: 'preview',
    // component: resolve => { require(['@/views/form/article-publish/preview.vue'], resolve); }
};

export const locking = {
    path: '/locking',
    name: 'locking',
    component: resolve => { require(['@/views/index/lockscreen/components/locking-page.vue'], resolve); }
};

// 作为Main组件的子页面展示但是不在左侧菜单显示的路由写在otherRouter里
export const otherRouter = {
    path: '/',
    name: 'otherRouter',
    // redirect: '/home',
    component: Main,
    children: [
        { path: 'home', title: {i18n: '首页'}, meta: {title:'首页'}, name: 'home_index', component: resolve => { require(['@/views/home/index.vue'], resolve); } },
        { path: 'userInfo/:id', title: {i18n: '用户详情'}, meta: {title:'用户详情',keepAlive: false}, name: 'userInfo', component: resolve => { require(['__userSearch/userInfo.vue'], resolve) }},
        { path: 'sysDeptHandle', title:{i18n: '部门管理'}, meta: {title:'部门管理'}, name: 'sysDeptHandle', component: resolve => { require(['@/views/system/dept/handle.vue'], resolve); } },
        { path: 'sysDeptHandle/:id', title:{i18n: '部门管理'},  meta: {title:'部门管理'},name: 'sysDeptHandleEdit', component: resolve => { require(['@/views/system/dept/handle.vue'], resolve); } },
        { path: 'sysRoleHandle', title:{i18n: '角色管理'},  meta: {title:'角色管理'},name: 'sysRoleHandle', component: resolve => { require(['@/views/system/role/handle.vue'], resolve); } },
        { path: 'sysRoleHandle/:id', title:{i18n: '角色管理'}, meta: {title:'角色管理'}, name: 'sysRoleHandleEdit', component: resolve => { require(['@/views/system/role/handle.vue'], resolve); } },
        { path: 'sysUserHandle', title:{i18n: '管理员管理'}, meta: {title:'管理员管理'}, name: 'sysUserHandle', component: resolve => { require(['@/views/system/user/handle.vue'], resolve); } },
        { path: 'sysUserHandle/:id', title:{i18n: '管理员管理'}, meta: {title:'管理员管理'}, name: 'sysUserHandleEdit', component: resolve => { require(['@/views/system/user/handle.vue'], resolve); } },
        { path: 'addBanner', title:{i18n: '添加banner'}, meta: {title:'添加banner'}, name: 'addBanner', component: resolve => { require(['@/views/operate/ContentManagement/banner/form'], resolve); } },
        { path: 'editBanner/:id', title:{i18n: '编辑banner'}, meta: {title:'编辑banner'}, name: 'editBanner', component: resolve => { require(['@/views/operate/ContentManagement/banner/form'], resolve); } },
        { path: 'addDownload', title:{i18n: '添加下载地址'}, meta: {title:'添加下载地址'}, name: 'addDownload', component: resolve => { require(['@/views/operate/ContentManagement/download/form'], resolve); } },
        { path: 'eidtDownload/:id', title:{i18n: '编辑下载地址'}, meta: {title:'编辑下载地址'}, name: 'eidtDownload', component: resolve => { require(['@/views/operate/ContentManagement/download/form'], resolve); } }
    ]
};
// 作为Main组件的子页面展示并且在左侧菜单显示的路由写在appRouter里
export const appRouter = [
    {
        path: '/',
        icon: 'ios-person-outline',
        name: '用户管理',
        meta: {title:'用户管理'},
        title: {i18n: '用户管理'},
        perm: [
            'page:user:mgt',
            'page:user:mgt:query',
            'page:user:audit:list',
            'user:mgt:query:list',
            'user:mgt:query:account',
            'user:mgt:query:detail',
            'user:remark:add',
            'user:remark:show',
            'user:remark:del',
            'user:mgt:query:asset',
            'user:mgt:query:asset:list',
            'user:mgt:query:fince',
            'user:mgt:query:fince:list',
            'user:mgt:query:entrust',
            'user:mgt:query:entrust:list',
            'user:mgt:query:complete',
            'user:mgt:query:complete:list',
            'user:mgt:query:security',
            'user:mgt:query:note',
            'user:remark:type:add',
            'user:remark:type:del'
        ],
        component: Main,
        children: [
            { path: '/userSearch', title: {i18n: '用户查询'},meta: {title:  '用户查询'}, perm:
            ['page:user:mgt:query',
            'user:mgt:query:list',
            'user:mgt:query:detail',
            'user:mgt:query:account',
            'user:remark:add',
            'user:remark:show',
            'user:remark:del',
            'user:mgt:query:asset',
            'user:mgt:query:asset:list',
            'user:mgt:query:fince',
            'user:mgt:query:fince:list',
            'user:mgt:query:entrust',
            'user:mgt:query:entrust:list',
            'user:mgt:query:complete',
            'user:mgt:query:complete:list',
            'user:mgt:query:security',
            'user:mgt:query:note',
            'user:remark:type:add',
            'user:remark:type:del'
          ],
             name: '用户查询', component: resolve => { require(['__userSearch/userSearch.vue'], resolve) } },
            // { path: '/userAuth', title: {i18n: '用户认证'},meta: {title: '用户认证'}, perm:
            { path: '/userAuth', title: {i18n: '用户认证'},meta: {title: '用户认证'}, perm:
            process.env.TYPE === 'kr'?["auth:refuse",
                "audit:check:check",
                "auth:white:revoke",
                "audit:check:list",
                "auth:refuse:add",
                "auth:refuse:edit",
                "audit:check",
                "page:user:audit:list",
                "audituser:whitelist:query",
                "auth:white:pass",
                "audituser:whitelist",
                "auth:refuse:del"
            ]:['page:user:audit:list'], name: '用户认证', component: resolve => { require(['__userAuth/userAuth.vue'], resolve) } },
        ]
    },
    {
        path: '/',
        icon: 'ios-browsers-outline',
        name: '交易所管理',
        meta:{title: '交易所管理'},
        title: {i18n: '交易所管理'},
        perm: [
            'page:pro:trade',
            'page:pro:currency:introduction',
            'page:pro:settings:currency',
            'pro:currency:introduction:select:list',
            'pro:currency:introduction:select:save',
            'pro:currency:introduction:select:update',
            'pro:settings:currencyName:list',
            'pro:settings:symbols:symbolName',
            'pro:settings:currency:list',
            'pro:settings:currency:statusCount',
            'pro:settings:currency:currencyInfo',
            'pro:settings:currency:updateSimple',
            'pro:settings:symbol:list',
            'pro:settings:symbol:statusCount',
            'pro:settings:symbol:symbolInfo',
            'pro:settings:symbol:updateSimple',
            'pro:trade',
            'pro:operate:tradeRule',
            'tab:job:hbprosymbols',
            'job:hbprosymbols:update',
            'job:hbprosymbols:list',
            'tab:job:hbhadaxsymbols',
            'job:hbhadaxsymbols:list',
            'job:hbhadaxsymbols:update'
        ],
        component: Main,
        children: [
            { path: '/coinSetting',title: {i18n: '币种设置'}, perm: ['page:pro:currency:introduction','pro:currency:introduction:select:list',
                    'pro:currency:introduction:select:save',
                    'pro:currency:introduction:select:update',], meta:{title: '币种设置'}, name: '币种设置', component: resolve => { require(['__views/exchange/index.vue'], resolve); } },
            { path: '/symbolSetting',title:  {i18n: '交易对设置'}, perm: ['page:pro:settings:currency',
                    'pro:settings:currencyName:list',
                    'pro:settings:symbols:symbolName',
                    'pro:settings:currency:list',
                    'pro:settings:currency:statusCount',
                    'pro:settings:currency:currencyInfo',
                    'pro:settings:currency:updateSimple',
                    'pro:settings:symbol:list',
                    'pro:settings:symbol:statusCount',
                    'pro:settings:symbol:symbolInfo',
                    'pro:settings:symbol:updateSimple',
                    'pro:trade',
                    'pro:operate:tradeRule',
                    'tab:job:hbprosymbols',
                    'job:hbprosymbols:update',
                    'job:hbprosymbols:list',
                    'tab:job:hbhadaxsymbols',
                    'job:hbhadaxsymbols:list',
                    'job:hbhadaxsymbols:update'], meta:{title: '交易对设置'}, name: '交易对设置', component: resolve => { require(['__views/exchange/symbolSetting.vue'], resolve); } },
            // { path: '/symbolRule',title: {i18n: '交易规则设置'}, perm: ['page:pro:operate:tradeRule','pro:operate:tradeRule:list','pro:operate:tradeRule:update','pro:operate:tradeRule:del',], meta:{title: '交易规则设置'}, name: '交易规则设置', component: resolve => { require(['__views/exchange/symbolSetting.vue'], resolve); } },
            // { path: '/userOtherService',title: {i18n: '流动性设置'}, meta:{title: '流动性设置'}, name: '流动性设置', component: resolve => { require(['@/views/error-page/404.vue'], resolve); } },
        ]
    },
    // {
    //     path: '/',
    //     icon: 'ios-pie-outline',
    //     name: '系统统计',
    //     meta:{title:  '系统统计'},
    //     title: {i18n: '系统统计'},
    //     perm: ['page:statistics',
    //         'page:statistics:listBase',
    //         'page:statistics:trade',
    //         'page:statistics:lconversion',
    //         'page:statistics:user',
    //         'statistics:listBase',
    //         'statistics:listBaseExport',
    //         'statistics:listDetail',
    //         'statistics:listDetailExport',
    //         'statistics:getTradeNumber',
    //         'statistics:getTradeNumberExport',
    //         'statistics:getTradeFee',
    //         'statistics:getTradeFeeExport',
    //         'statistics:listConversion',
    //         'statistics:listConversionExport',
    //         'statistics:listConversion7',
    //         'statistics:listConversion7Export',
    //     ],
    //     component: Main,
    //     children: [
    //         {
    //             path: '/baseCount',
    //             name: '基础统计',
    //             meta:{title:  '基础统计'},
    //             perm: ['page:statistics:listBase',
    //                 'statistics:listBase',
    //                 'statistics:listBaseExport',
    //                 'statistics:listDetail',
    //                 'statistics:listDetailExport',],
    //             title: {i18n: '基础统计'},
    //             component: resolve => { require(['__views/systemStatistics/baseCount/baseCount.vue'], resolve)}
    //         },
    //         {
    //             path: '/tradeCount',
    //             name: '交易统计',
    //             meta:{title:  '交易统计'},
    //             perm: ['page:statistics:trade',
    //                 'statistics:getTradeNumber',
    //                 'statistics:getTradeNumberExport',
    //                 'statistics:getTradeFee',
    //                 'statistics:getTradeFeeExport',
    //             ],
    //             title: {i18n: '交易统计'},
    //             component: resolve => { require(['__tradeCount/tradeCount.vue'], resolve)} },
    //         {
    //             path: '/transformCount',
    //             name: '转化统计',
    //             meta:{title:  '转化统计'},
    //             perm: ['page:statistics:lconversion',
    //                 'statistics:listConversion',
    //                 'statistics:listConversionExport',
    //                 'statistics:listConversion7',
    //                 'statistics:listConversion7Export',
    //             ],
    //             title: {i18n: '转化统计'},
    //             component: resolve => { require(['__views/systemStatistics/transformCount/transform.vue'], resolve)}
    //         },
    //         {
    //             path: '/userInfoCount',
    //             name: '用户信息统计',
    //             meta:{title:  '用户信息统计'},
    //             title: {i18n: '用户信息统计'},
    //             component: resolve => { require(['__views/systemStatistics/userInfoCount/userInfoMune.vue'], resolve)}
    //         },
    //     ]
    // },
    {
        path: '/',
        icon: 'social-yen-outline',
        name: '财务管理',
        meta:{title:  '财务管理'},
        title: {i18n: '财务管理'},
        perm: ['page:pro:fince',
            'page:pro:fince:system:accounts',
            'page:pro:fince:system:assets',
            'page:pro:fince:system:operation',
            'page:pro:fince:coperation',
            'pro:fince:system:accounts:detail',
            'pro:fince:system:assets:list',
            'pro:fince:system:assets:update',
            'pro:fince:system:assets:history',
            'pro:fince:system:assets:historyList',
            'pro:fince:system:assets:historyListExp',
            'pro:fince:system:operation:list',
            'pro:fince:system:operation:updateAccounts',
            'pro:fince:system:operation:updateAccounts',
            'pro:fince:system:operation:historyList',
            'pro:fince:system:operation:historyListExp',
            'pro:fince:operation:accountsList',
            'pro:fince:operation:updateAccounts',
            'pro:fince:operation:updateAccounts',
            'pro:fince:operation:getTransferUser',
            'pro:fince:operation:transferToUser',
            'pro:fince:operation:transferToUser',
            'pro:fince:operation:accountsHistory',
            'pro:fince:operation:accountsHistoryExp',
            'pro:fince:operation:approveList',
            'pro:fince:operation:approve',
            'page:pro:fince:walletAssets',
        ],
        component: Main,
        children: [
            {path: '/accountDetails',name: "账户明细查询", perm: ['page:pro:fince:system:accounts','pro:fince:system:accounts:detail',], title: {i18n: '账户明细查询'}, meta:{title:  '账户明细查询'},component: resolve => { require(['__views/finance/accountDetails/index.vue'], resolve)}},
            {path: '/withCapital',name: "总账户配资", perm:['page:pro:fince:system:assets','pro:fince:system:assets:list',
                    'pro:fince:system:assets:update',
                    'pro:fince:system:assets',
                    'pro:fince:system:assets:reduce',
                    'pro:fince:system:assets:increase',
                    'pro:fince:system:assets:history',
                    'pro:fince:system:assets:historyList',
                    'pro:fince:system:assets:historyListExp',], title: {i18n: '总账户配资'}, meta:{title:  '总账户配资'},component: resolve => { require(['__views/finance/withCapital/index.vue'], resolve)}},
            {path: '/transfer',name: "总账户划拨", perm:['page:pro:fince:system:operation','pro:fince:system:operation:list',
                    'pro:fince:system:operation:history',
                    'pro:fince:system:operation',
                    'pro:fince:system:operation:updateAccounts',
                    'pro:fince:system:operation:historyList',
                    'pro:fince:system:operation:historyListExp',], title: {i18n: '总账户划拨'}, meta:{title:  '总账户划拨'},component: resolve => { require(['__views/finance/transfer/index.vue'], resolve)}},
            {path: '/operationOperation',name: "运营账户操作", perm:['page:pro:fince:coperation','pro:fince:operation:accountsList',
                    'pro:fince:operation:updateAccounts',
                    'pro:fince:operation:account',
                    'pro:fince:operation:user',
                    'pro:fince:operation:history',
                    'pro:fince:operation:approveList',
                    'pro:fince:operation:updateAccounts',
                    'pro:fince:operation:getTransferUser',
                    'pro:fince:operation:transferToUser',
                    'pro:fince:operation:accountsHistory',
                    'pro:fince:operation:accountsHistoryExp',
                    'pro:fince:operation:approve'], title: {i18n: '运营账户操作'}, meta:{title:  '运营账户操作'},component: resolve => { require(['__views/finance/operationOperation/index.vue'], resolve)}},
            // {path: '/walletAsset',name: "钱包资产统计", perm:['page:pro:fince:walletAssets'], title: {i18n: '钱包资产统计'}, meta:{title:  '钱包资产统计'},component: resolve => { require(['__views/finance/walletAsset/walletMune.vue'], resolve)}},
            {path: '/cautionMoney',name: "保证金管理", perm:[
                'page:pro:margin',
                'tab:fince:margin:mgtInPro',
                'tab:fince:margin:proInMgt',
                'tab:fince:transfer:history',
                'fince:margin:mgtInPro:list',
                'fince:margin:mgtInPro:update',
                'fince:margin:mgtInPro:offline',
                'fince:margin:proInMgt:list',
                'fince:transfer:history:list',
                'fince:transfer:history:export'

            ], title: {i18n: '保证金管理'}, meta:{title:  '保证金管理'},component: resolve => { require(['__views/finance/cautionMoney/index.vue'], resolve)}},
            {path: '/financialStatements',name: "财务报表", perm:[
                'page:pro:margin',
                'tab:fince:margin:mgtInPro',
                'tab:fince:margin:proInMgt',
                'tab:fince:transfer:history',
                'fince:margin:mgtInPro:list',
                'fince:margin:mgtInPro:update',
                'fince:margin:mgtInPro:offline',
                'fince:margin:proInMgt:list',
                'fince:transfer:history:list',
                'fince:transfer:history:export'

            ], title: {i18n: '财务报表'}, meta:{title:  '财务报表'},component: resolve => { require(['__views/finance/statements/statements.vue'], resolve)}}
        ]
    },
    {
        path: '/',
        icon: 'ios-settings',
        name: '风控管理',
        meta:{title:  '风控管理'},
        title:  {i18n: '风控管理'},
        perm: ['page:risk',
            'page:risk:specialUsers',
            'page:risk:black',
            // 'page:risk:management',
            'risk:management:blacklist',
            'risk:management:userBlackInfo',
            'risk:management:updateBlack',
            'risk:management:list',
            'risk:management:update',
            'risk:specialUsers:list',
            'risk:specialUsers:info',
            'risk:specialUsers:update',
            'risk:specialAmountManager:list',
            'risk:specialAmountUser:list'
        ],
        component: Main,
        children: [
            {
                path: '/common',
                name: '通用额度设置',
                perm: ['risk:management:update',
                        'risk:management:thawBlack',
                       'risk:management:list'],
                meta:{title:  '通用额度设置'},
                title:  {i18n: '通用额度设置'},
                component: resolve => { require(['__views/riskManagement/common/common.vue'], resolve)}
            },
            {path: '/special',name: "特殊用户额度设置", perm: ['page:risk:specialUsers','risk:specialUsers:list',
                    'risk:specialUsers:info',
                    'risk:specialUsers:update',
                    'risk:specialAmountManager',
                    'risk:specialAmountManager:list',
                    'risk:specialAmountUser:list'], title:  {i18n: '特殊用户额度设置'}, meta:{title:  '特殊用户额度设置'},component: resolve => { require(['__views/riskManagement/special/special.vue'], resolve)}},
            // {path: '/getLimit',name: "自动提币审核设置", perm: ['page:risk:management','risk:management:list','risk:management:update',], title: {i18n: '自动提币审核设置'}, meta:{title:  '自动提币审核设置'},component: resolve => { require(['__views/riskManagement/getLimit/getLimit.vue'], resolve)}},
            {path: '/blackLimit',name: "黑名单设置", perm:['page:risk:black','risk:management:blacklist',
                    'risk:management:userBlackInfo',
                    'risk:management:blacklistinfo',
                    'risk:management:updateBlack',], title:  {i18n: '黑名单设置'}, meta:{title:  '黑名单设置'},component: resolve => { require(['__views/riskManagement/blackLimit/blackLimit.vue'], resolve)}}
        ]
    },
    {
        path: '/',
        icon: 'ios-gear-outline',
        name: '系统管理',
        meta:{title:  '系统管理'},
        title: {i18n: '系统管理'},
        component: Main,
        perm: [
            'sys:user:save',
            'sys:user:update',
            'sys:user:delete',
            'sys:user:list',
            'sys:user:password',
            'sys:dept:save',
            'sys:dept:update',
            'sys:dept:delete',
            'sys:dept:list',
            'sys:role:save',
            'sys:role:update',
            'sys:role:delete',
            'sys:role:list',
            'sys:menu:save',
            'sys:menu:update',
            'sys:menu:delete',
            'sys:menu:list',
            'sys:schedule:save',
            'sys:schedule:update',
            'sys:schedule:delete',
            'sys:schedule:list',
            'sys:schedule:pause',
            'sys:schedule:resume',
            'sys:schedule:run',
            'sys:scheduleLog:list',
            'sys:config:save',
            'sys:config:update',
            'sys:config:delete',
            'sys:config:list',
            'sys:oss:upload',
            'sys:oss:delete',
            'sys:oss:list',
            'sys:oss:saveConfig',
            'sys:log:list',
            'page:sys',
            'page:sys:user',
            'page:sys:dept',
            'page:sys:role',
            'sys:user:resetPass'
        ],
        children: [
            {path: '/sysUser',name: '管理员管理',title: {i18n: '管理员管理'},
                perm: ['page:sys:user',
                    'sys:user:save',
                    'sys:user:update',
                    'sys:user:delete',
                    'sys:user:list',
                    'sys:user:resetPass',
                    'sys:user:password'], meta:{title:  '管理员管理'},component: resolve => { require(['__views/system/user/user.vue'], resolve)}},
            {path: '/sysDept',name: '部门管理',title: {i18n: '部门管理'},
                perm: [
                    'page:sys:dept',
                    'sys:dept:save',
                    'sys:dept:update',
                    'sys:dept:delete',
                    'sys:dept:list',], meta:{title:  '部门管理'},component: resolve => { require(['__views/system/dept/dept.vue'], resolve)}},
            {path: "/sysRole", name: "角色管理",title: {i18n: '角色管理'},
                perm: ['page:sys:role','sys:role:save',
                    'sys:role:update',
                    'sys:role:delete',
                    'sys:role:list',], meta:{title:  '角色管理'},  component: resolve => { require(['__views/system/role/role.vue'], resolve)}},
            // {path: "/menu", name: "菜单管理",title: {i18n: '菜单管理'}, perm: ['page:sys:menu','sys:menu:save','sys:menu:update','sys:menu:delete','sys:menu:list',], meta:{title:  '菜单管理'},  component: resolve => { require(['@/views/system/menu.vue'], resolve)}},
            // {path: "/timeTask", name: "定时任务",title: {i18n: '定时任务'}, perm: ['page:sys:schedule','sys:schedule:save','sys:schedule:update','sys:schedule:delete','sys:schedule:list','sys:schedule:pause','sys:schedule:resume','sys:schedule:run',], meta:{title:  '定时任务'},  component: resolve => { require(['@/views/system/timeTask.vue'], resolve)}},
            // {path: "/taskLog", name: "日志列表",title: {i18n: '日志列表'}, perm: ['page:sys:scheduleLog','sys:scheduleLog:list',], meta:{title:  '日志列表'},  component: resolve => { require(['@/views/system/taskLog.vue'], resolve)}},
            // {path: "/config", name: "参数管理",title: {i18n: '参数管理'}, perm: ['page:sys:config','sys:config:save','sys:config:update','sys:config:delete','sys:config:list',], meta:{title:  '参数管理'},  component: resolve => { require(['__views/system/config.vue'], resolve)}},
            // {path: "/fileUpload", name: "文件上传",title: {i18n: '文件上传'}, perm: ['page:sys:oss','sys:oss:upload','sys:oss:delete','sys:oss:list','sys:oss:saveConfig',], meta:{title:  '文件上传'},  component: resolve => { require(['__views/system/fileUpload/fileUpload.vue'], resolve)}},
        ]
    },
];
if ( process.env.TYPE === 'kr' ) {

    for (let item of appRouter) {
        if ( item.name === '系统管理' ) {
            // 添加系统日志
            item.children.push({path: "/systemLog", name: "系统日志",title: {i18n: '系统日志'}, perm: ['page:sys:log','sys:log:list',], meta:{title:  '系统日志'},  component: resolve => { require(['__views/system/systemLog.vue'], resolve)}})
        }
    }
    // 法币管理
    appRouter.push(
        {
            path: '/',
            icon: 'social-usd-outline',
            name: '法币管理',
            meta:{title:  '法币管理'},
            title: {i18n: '法币管理'},
            component: Main,
            children: [
                {
                    path: "/autoQuery",
                    name: "收款管理",
                    title: {i18n: '收款管理'},
                    perm: [
                        'page:legal:hbreceiptaccount',
                        'tab:legal:hbreceiptaccount:bank',
                        'tab:legal:hbreceipt:hbvipcustomer',

                        'manuallegal:hbreceiptaccount:list',
                        'manuallegal:hbreceiptaccount:save',
                        'manuallegal:hbreceiptaccount:update',
                        'manuallegal:hbreceiptaccount:delete',

                        'manuallegal:hbreceiptaccount:updateUseStatus',
                        'manuallegal:hbreceiptaccount:getUrl',

                        'manuallegal:hbvipcustomer:list',
                        'manuallegal:hbvipcustomer:add',
                        'manuallegal:hbvipcustomer:open:close',
                        'manuallegal:hbvipcustomer:del',
                        'manuallegal:hbvipcustomer:batchAdd',
                        'manuallegal:hbvipcustomer:execl'
                    ],
                    meta:{title:  '收款管理'},  component: resolve => { require(['@/views/legalTender/autoQuery/autoQuery.vue'], resolve)}},
                {
                    path: "/legal/charge",
                    name: "法币充值管理",
                    title: {i18n: '法币充值管理'},
                    meta:{title:  '法币充值管理'},
                    perm: [
                        'tab:lmanuallegal:hbdepositapply',
                        'tab:manuallegal:hbdepositbankflow',
                        'tab:manuallegal:hbdepositapplyreview',
                        'tab:manuallegal:hbuploadbankflow',
                        'manuallegal:hbdepositapply:list',
                        'manuallegal:hbdepositapply:save',
                        'manuallegal:hbdepositapplymatch:match',
                        'manuallegal:hbdepositapplymatch:cancel',
                        'manuallegal:hbdepositapplymatch:undo',
                        'manuallegal:hbdepositbankflow:list',
                        'manuallegal:hbdepositbankflow:more',
                        'manuallegal:hbdepositbankflow:updateState',
                        'manuallegal:hbdepositbankflow:save',
                        'manuallegal:hbdepositapplyreview:list',
                        'manuallegal:hbdepositapplyreview:info',
                        'manuallegal:hbdepositapplyreview:reject',
                        'manuallegal:hbdepositapplyreview:accept',
                        'manuallegal:hbuploadbankflow:upload',
                        'manuallegal:hbuploadbankflow:query',
                        'manuallegal:hbuploadbankflow:save',
                        'manuallegal:hbuploadbankflow:execl'
                    ],
                    component: resolve => { require(['@/views/legalTender/charge'], resolve)}
                },
                {path: "/legalWithdraw",perm:[
                    'page:legal:withdrawls',
                    'tab:legal:withdrawls:trial',
                    'tab:legal:withdrawls:review',
                    'tab:legal:withdrawls:wait',
                    'tab:legal:withdrawls:query',
                    'tab:legal:withdrawls:refuse',

                    'legal:withdrawls:trial:list',
                    'legal:withdrawls:trial:refused',
                    'legal:withdrawls:trial:submitReview',
                    'legal:withdrawls:trial:pass',
                    'legal:withdrawls:review:list',

                    'legal:withdrawls:confirmation',
                    'legal:withdrawls:wait:list:exp',
                    'legal:withdrawls:wait:batchConfirm',




                    'legal:withdrawls:review:refused',
                    'legal:withdrawls:review:pass',
                    'legal:withdrawls:confirmation',
                    'legal:withdrawls:refuse:list',
                    'legal:withdrawls:refuse:add',
                    'legal:withdrawls:refuse:edit',
                    'legal:withdrawls:refuse:del'
                ], name: "提现管理",title: {i18n: '提现管理'}, meta:{title:  '提现管理'},  component: resolve => { require(['@/views/legalTender/withdraw/withdraw.vue'], resolve)}},
                // {
                //     path: "/currencyLimit",
                //     name: "提现限额设置",
                //     title: {i18n: '提现限额设置'},
                //     meta:{title:  '提现限额设置'},
                //     perm:[
                //         'page:legal:withdrawlegalsetting',
                //         'tab:legal:withdrawlegalsetting',
                //         'tab:legal:withdrawlegalgroup',
                //         'tab:legal:withdrawlegalgroupuser',
                //
                //         'legal:withdrawlegalsetting:list',
                //         'legal:withdrawlegalsetting:update',
                //         'legal:withdrawlegalgroup:list',
                //         'legal:withdrawlegalgroup:addUser',
                //         'legal:withdrawlegalgroup:delete',
                //         'legal:withdrawlegalgroup:save',
                //         'legal:withdrawlegalgroup:update',
                //         'legal:withdrawlegalgroupuser:list',
                //         'legal:withdrawlegalgroupuser:delete'
                //     ],
                //     component: resolve => { require(['@/views/legalTender/currencyLimit/limitMune.vue'], resolve)}},
                // {path: "/autoQuery", name: "自动充值查询",title: {i18n: '自动充值查询'}, meta:{title:  '自动充值查询'},  component: resolve => { require(['@/views/legalTender/autoQuery/autoQuery.vue'], resolve)}}
            ]
        },
        {
            path: '/',
            icon: 'ios-pulse',
            name: '运营管理',
            meta:{title:  '运营管理'},
            title: {i18n: '运营管理'},
            perm: ['page:pro:operate',
                'page:trade:fee',
                'page:dawn:operate',
                'page:pro:content:notice',
                'page:content',
                'trade:fee:list',
                'trade:fee:update',
                'trade:fee:group:list',
                'trade:fee:group:list:exp',
                'trade:fee:group:delete',
                'withdraw:fees:list',
                'withdraw:fees:update',
                'dawn:operate:activity:list',
                'dawn:operate:activity:detail',
                'dawn:operate:activity:add',
                'dawn:operate:activity:detail',
                'dawn:operate:activity:approve',
                'trade:fee:group:add',
                'trade:fee:group:add',
                'pro:content:notice:list',
                'pro:content:notice:top',
                'pro:content:notice:delete',
                'pro:content:notice:top',
                'pro:content:notice:update',
                'pro:content:notice:add',
                'content:banner:list',
                'content:banner:delete',
                'content:banner:add',
                'content:banner:update',
                'content:download:list',
                'content:download:update',
                'content:download:add',
                'content:download:delete',
            ],
            component: Main,
            children: [
                {
                    path: '/rateSetting',
                    name: '费率设置',
                    meta:{title:  '费率设置'},
                    perm: ['page:trade:fee',
                        'trade:fee:list',
                        'trade:fee:update',
                        'trade:fee:group:list',
                        'trade:fee:group:list:exp',
                        'trade:fee:group:delete',
                        'withdraw:fees:update',
                        'trade:fee:list',
                        'trade:fee:group:list',
                        'withdraw:fees:list'
                    ],
                    title: {i18n: '费率设置'},
                    component: resolve => { require(['__views/operate/rateSetting/operateMune.vue'], resolve)}
                },
                {path: '/transferAccounts',name: "运营批量转款", perm: ['page:dawn:operate','dawn:operate:activity:list',
                        'dawn:operate:activity:detail',
                        'dawn:operate:activity:add',
                        'dawn:operate:activity',
                        'dawn:operate:activity:check',
                        'dawn:operate:activity:detail',
                        'dawn:operate:activity:approve',
                        ], title: {i18n: '运营批量转款'}, meta:{title:  '运营批量转款'},component: resolve => { require(['__views/operate/transferAccounts/index.vue'], resolve)}},
                {path: '/notice',name: "公告管理",title: {i18n: '公告管理'}, perm: ['page:pro:content:notice',
                        'pro:content:notice:list',
                        'pro:content:notice:top',
                        'pro:content:notice:delete',
                        'pro:content:notice:top',
                        'pro:content:notice:update',
                        'pro:content:notice:add',],  meta:{title:  '公告管理'},component: resolve => { require(['__views/operate/notice/index.vue'], resolve)}},
                {path: '/contentManage',name: "contentManage", perm: [
                        'page:content',
                        'content:banner:list',
                        'content:banner:delete',
                        'content:banner:add',
                        'content:banner:update',
                        'content:download:list',
                        'content:download:update',
                        'content:download:add',
                        'content:download:delete',], title: {i18n: '内容管理'}, meta:{title:  '内容管理'},component: resolve => { require(['__views/operate/ContentManagement'], resolve)}},
                {path: '/versionManage', perm:[

                    'page:oper:hbterminalversion',
                    'tab:oper:hbterminalversion',
                    'oper:hbterminalversion:list',
                    'oper:hbterminalversion:insert',
                    'oper:hbterminalversion:update',
                    'oper:hbterminalversion:info',
                    'oper:hbterminalversion:delete',
                ],name: "versionManage", title: {i18n: '版本管理'}, meta:{title:  '版本管理'},component: resolve => { require(['__views/operate/version/versionMune.vue'], resolve)}},
                {path: '/appManage',name: "APP法币功能总控",title: {i18n: 'APP法币功能总控'}, perm: [
                    'page:oper:hblegalswitch',
                    'tab:oper:hblegalswitch',
                    'oper:hblegalswitch:list',
                    'oper:hblegalswitch:save',
                    'oper:hblegalswitch:update',
                    'oper:hblegalswitch:delete',],  meta:{title:  'APP法币功能总控'},component: resolve => { require(['__views/operate/appManagement/index.vue'], resolve)}}
            ]
        },
        {
            path: '/',
            icon: 'key',
            icon: 'ios-shuffle',
            name: '充提管理',
            meta:{title:  '充提管理'},
            title: {i18n: '充提管理'},
            perm : [
                'page:withdrawmanager',
                'page:withdraw',
                'withdraw:list',
                'withdraw:status',
                'withdraw:pass',
                'withdraw:refuse',
                'withdraw:submit',
                'withdraw:fCheck:list',
                'withdraw:fCheck:refuse',
                'withdraw:fCheck:submit',
                'withdraw:fCheck:pass',
                'withdraw:rCheck:list',
                'withdraw:rCheck:refuse',
                'withdraw:rCheck:pass',
                'withdraw:refuse:list',
                'withdraw:refuse:add',
                'withdraw:refuse:edit',
                'withdraw:refuse:del',
                'page:deposit'
            ],
            component: Main,
            children: [
                {
                    path: '/digitalAssets',
                    icon: '',
                    perm: ['page:withdraw',
                        'withdraw:list',
                        'withdraw:status',
                        'withdraw:pass',
                        'withdraw:refuse',
                        'withdraw:submit',
                        'withdraw:fCheck:list',
                        'withdraw:fCheck:refuse',
                        'withdraw:fCheck:submit',
                        'withdraw:fCheck:pass',
                        'withdraw:rCheck:list',
                        'withdraw:rCheck:refuse',
                        'withdraw:rCheck:pass',
                        'withdraw:refuse:list',
                        'withdraw:refuse:add',
                        'withdraw:refuse:edit',
                        'withdraw:refuse:del',],
                    name: '数字资产提币',
                    meta:{title:  '数字资产提币'},
                    title: {i18n: '数字资产提币'},
                    component: resolve => {
                        require(['__views/ManageRecharge/digitalAssets/index.vue'], resolve)
                    }
                },
                {
                    path: '/digitalAssets/charge',
                    // icon: 'key',
                    name: '数字资产充币',
                    perm : [
                        'page:deposit',
                    ],
                    meta:{title:  '数字资产充币'},
                    title: {i18n: '数字资产充币'},
                    component: resolve => {
                        require(['__views/ManageRecharge/charge.vue'], resolve)
                    }
                }
            ]
        },
    )
} else {
    appRouter.push(
        {
            path: '/',
            icon: 'ios-shuffle',
            name: '充提管理',
            meta:{title:  '充提管理'},
            title: {i18n: '充提管理'},
            perm : [
                'page:withdrawmanager',
                'page:withdraw',
                'withdraw:list',
                'withdraw:status',
                'withdraw:pass',
                'withdraw:refuse',
                'withdraw:submit',
                'withdraw:fCheck:list',
                'withdraw:fCheck:refuse',
                'withdraw:fCheck:submit',
                'withdraw:fCheck:pass',
                'withdraw:rCheck:list',
                'withdraw:rCheck:refuse',
                'withdraw:rCheck:pass',
                'withdraw:refuse:list',
                'withdraw:refuse:add',
                'withdraw:refuse:edit',
                'withdraw:refuse:del',
                'page:deposit'
            ],
            component: Main,
            children: [
                {
                    path: '/digitalAssets',
                    // icon: 'key',
                    perm: ['page:withdraw',
                        'withdraw:list',
                        'withdraw:status',
                        'withdraw:pass',
                        'withdraw:refuse',
                        'withdraw:submit',
                        'withdraw:fCheck:list',
                        'withdraw:fCheck:refuse',
                        'withdraw:fCheck:submit',
                        'withdraw:fCheck:pass',
                        'withdraw:rCheck:list',
                        'withdraw:rCheck:refuse',
                        'withdraw:rCheck:pass',
                        'withdraw:refuse:list',
                        'withdraw:refuse:add',
                        'withdraw:refuse:edit',
                        'withdraw:refuse:del',],
                    name: '数字资产提币',
                    meta:{title:  '数字资产提币'},
                    title: {i18n: '数字资产提币'},
                    component: resolve => {
                        require(['__views/ManageRecharge/digitalAssets/index.vue'], resolve)
                    }
                },
                {
                    path: '/digitalAssets/charge',
                    // icon: 'key',
                    name: '数字资产充币',
                    perm : [
                        'page:deposit',
                    ],
                    meta:{title:  '数字资产充币'},
                    title: {i18n: '数字资产充币'},
                    component: resolve => {
                        require(['__views/ManageRecharge/charge.vue'], resolve)
                    }
                }
            ]
        },
        {
            path: '/',
            icon: 'ios-pulse',
            name: '运营管理',
            meta:{title:  '运营管理'},
            title: {i18n: '运营管理'},
            perm: ['page:pro:operate',
                'page:trade:fee',
                'page:dawn:operate',
                'page:pro:content:notice',
                'page:content',
                'trade:fee:list',
                'trade:fee:update',
                'trade:fee:group:list',
                'trade:fee:group:list:exp',
                'trade:fee:group:delete',
                'withdraw:fees:list',
                'withdraw:fees:update',
                'dawn:operate:activity:list',
                'dawn:operate:activity:detail',
                'dawn:operate:activity:add',
                'dawn:operate:activity:detail',
                'dawn:operate:activity:approve',
                'trade:fee:group:add',
                'trade:fee:group:add',
                'pro:content:notice:list',
                'pro:content:notice:top',
                'pro:content:notice:delete',
                'pro:content:notice:top',
                'pro:content:notice:update',
                'pro:content:notice:add',
                'content:banner:list',
                'content:banner:delete',
                'content:banner:add',
                'content:banner:update',
                'content:download:list',
                'content:download:update',
                'content:download:add',
                'content:download:delete',
            ],
            component: Main,
            children: [
                {
                    path: '/rateSetting',
                    name: '费率设置',
                    meta:{title:  '费率设置'},
                    perm: ['page:trade:fee',
                        'trade:fee:list',
                        'trade:fee:update',
                        'trade:fee:group:list',
                        'trade:fee:group:list:exp',
                        'trade:fee:group:delete',
                        'withdraw:fees:list',
                        'withdraw:fees:update',
                    ],
                    title: {i18n: '费率设置'},
                    component: resolve => { require(['__views/operate/rateSetting/operateMune.vue'], resolve)}
                },
                {path: '/transferAccounts',name: "运营批量转款", perm: ['page:dawn:operate','dawn:operate:activity:list',
                        'dawn:operate:activity:detail',
                        'dawn:operate:activity:add',
                        'dawn:operate:activity:detail',
                        'dawn:operate:activity:approve',
                        'trade:fee:group:add',
                        'trade:fee:group:add',], title: {i18n: '运营批量转款'}, meta:{title:  '运营批量转款'},component: resolve => { require(['__views/operate/transferAccounts/index.vue'], resolve)}},
                {path: '/notice',name: "公告管理",title: {i18n: '公告管理'}, perm: ['page:pro:content:notice',
                        'pro:content:notice:list',
                        'pro:content:notice:top',
                        'pro:content:notice:delete',
                        'pro:content:notice:top',
                        'pro:content:notice:update',
                        'pro:content:notice:add',],  meta:{title:  '公告管理'},component: resolve => { require(['__views/operate/notice/index.vue'], resolve)}},


            ]
        }
    )
}

// 所有上面定义的路由都要写在下面的routers里
export const routers = [
    loginRouter,
    otherRouter,
    // preview,
    locking,
    ...appRouter,
    page500,
    page403,
    page404
];
